import {
  AIComponent,
  AnimationComponent,
  Camera3DComponent,
  ChaseComponent,
  ColliderComponent,
  DamageComponent,
  DamageTextComponent,
  DeathMarkComponent,
  ExperienceComponent,
  HealthComponent,
  InputComponent,
  LifecycleComponent,
  LightSourceComponent,
  PhysicsComponent,
  PickupComponent,
  RenderComponent,
  ShapeComponent,
  SoundEffectComponent,
  SpiralMovementComponent,
  StateComponent,
  StatsComponent,
  TransformComponent,
  WeaponComponent,
} from '@ecs/components';
import { ComponentConstructor, EntityType, IComponent } from '../ecs/types';

export const EntityPoolList: EntityType[] = [
  'player',
  'enemy',
  'projectile',
  'weapon',
  'areaEffect',
  'damageText',
  'pickup',
  'effect',
  'other',
  'object',
  'obstacle',
  'light',
  'camera',
];

export const ComponentPoolList: ComponentConstructor<IComponent>[] = [
  RenderComponent,
  HealthComponent,
  AIComponent,
  ColliderComponent,
  PhysicsComponent,
  TransformComponent,
  DamageComponent,
  LifecycleComponent,
  InputComponent,
  ExperienceComponent,
  StatsComponent,
  WeaponComponent,
  PickupComponent,
  DamageTextComponent,
  DeathMarkComponent,
  ChaseComponent,
  SoundEffectComponent,
  SpiralMovementComponent,
  StateComponent,
  AnimationComponent,
  ShapeComponent,
  LightSourceComponent,
  Camera3DComponent,
];
